# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.subscriber.visit.events:
        class: AppBundle\Subscriber\VisitEventsSubscriber
        tags:
            - { name: kernel.event_subscriber }

    admin.subscriber.kernel.events:
        class: AdminBundle\Subscriber\KernelEventsSubscriber
        arguments: [ '@twig', '@session' ]
        tags:
            - { name: kernel.event_subscriber }

    admin.subscriber.category.form:
        class: AdminBundle\Subscriber\CategoryFormSubscriber
        tags:
            - { name: kernel.event_subscriber }

    admin.subscriber.user.form:
        class: AdminBundle\Subscriber\UserFormSubscriber
        tags:
            - { name: kernel.event_subscriber }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    admin.twig.extension:
        class: AdminBundle\Twig\AppExtension
        arguments: [ '@doctrine', '@twig' ]
        tags:
            - { name: twig.extension }

    admin.service.utils.strings:
        class: AdminBundle\Service\Utils\StringService

    admin.service.upload:
        class: AdminBundle\Service\UploadService
        arguments: [ '@admin.service.utils.strings', '%upload_dir%' ]

    admin.service.unlink:
        class: AdminBundle\Service\UnlinkService
        arguments: [ '%upload_dir%' ]

    admin.listener.product:
        class: AdminBundle\Listener\ProductListener
        arguments: [ '@admin.service.upload', '%upload_dir_default_img%', '@admin.service.unlink' ]
        tags:
            - { name: doctrine.orm.entity_listener }

    admin.listener.user:
        class: AdminBundle\Listener\UserListener
        arguments: [ '@admin.service.upload', '%upload_dir_default_img%', '@admin.service.unlink' ]
        tags:
            - { name: doctrine.orm.entity_listener }

