<?php

namespace AdminBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindqNumberCategory()
    {
        // Creation d'une requête DQL
        // findAll() maison
        $query = $this->getEntityManager()
            ->createQuery('
            SELECT COUNT(cat)
            FROM AdminBundle:Category cat
            ');
        return $query->getSingleScalarResult();

    }

    public function displayCategories()
    {
        $query = $this
            ->createQueryBuilder('category') // select * from product
            ->orderBy('category.title', 'DESC')
            ->getQuery()
        ;
        return $query->getResult();
    }

}
